
experiment_name: classical_exhaustive_n12

problem:
  n_key: 12
  objective_function: x0 + x1 + x2 + x3 + x4 + x5 - x6 - x7 + 2*x8 - 2*x9 + 0.5*x10 - 0.5*x11
  variable_type: spin

algorithm:
  method: classical_exhaustive

execution:
  num_trials: 1

simulation:
  backend: analytical
  max_iterations: 1
  seed: 0
