
experiment_name: qd_binary_nocircuit_uniform_infinite

problem:
  n_key: 10
  objective_function: x0 + x1 + x2 + x3 + x4 - 2*x5*x6 + 0.5*x7 + x8 - x9
  variable_type: binary

algorithm:
  method: qd
  initial_state: uniform

execution:
  num_trials: 50

simulation:
  backend: analytical
  convergence_backend: nocircuit
  qd_nocircuit_mode: infinite
  max_iterations: 256
  seed: 0

circuit_assets:
  build: true
