experiment_name: qd_binary_nocircuit_uniform

problem:
  n_key: 4
  n_val: 5
  objective_function: -x0 + x1 + x2 + x3
  variable_type: binary

algorithm:
  method: qd
  initial_state: uniform

simulation:
  backend: statevector
  # convergence_backend を書かなければ nocircuit が選ばれる想定
  convergence_backend: nocircuit
  qd_nocircuit_mode: fejer
  max_iterations: 20
  seed: 0

execution:
  num_trials: 10

circuit_assets: 
  build: true #trueにするとresultに回路図画像を生成

circuit_evaluation:
  optimization_level: 3 
  basis_gates: Default
