
experiment_name: qd_binary_nocircuit_w_state_fejer

problem:
  n_key: 8
  n_val: 6
  objective_function: x0 + x1 - x2 + 2*x3 - x4*x5 + 0.5*x6 + x7
  variable_type: binary

algorithm:
  method: qd
  initial_state: w_state

execution:
  num_trials: 50

simulation:
  backend: statevector
  convergence_backend: nocircuit
  qd_nocircuit_mode: fejer #Fejer分布を用いてn_valに対する挙動を高速にシミュレーション
  max_iterations: 40
  seed: 0

circuit_assets:
  build: true
