
experiment_name: qd_spin_nocircuit_dicke_infinite

problem:
  n_key: 10
  objective_function: x0 + x1 - x2 - x3 + 2*x4 - 2*x5 + x6 - x7 + x8 - x9
  variable_type: spin

algorithm:
  method: qd
  initial_state: dicke
  state_prep_params:
    k: 2

execution:
  num_trials: 50

simulation:
  backend: analytical
  convergence_backend: nocircuit
  qd_nocircuit_mode: infinite
  max_iterations: 256
  seed: 0

circuit_assets:
  build: true
