experiment_name: qsp_circuit_spin_example

problem:
  n_key: 2
  objective_function: x0 + x1 
  variable_type: spin

algorithm:
  method: qsp
  initial_state: uniform
  state_prep_params: {}
  qsp_params:
    qsp_degree: 9

simulation:
  convergence_backend: circuit
  backend: statevector
  max_iterations: 10
  seed: 1

execution:
  num_trials: 1000

circuit_assets:
  build: false

# circuit_evaluation:
#   optimization_level: 1
#   basis_gates: Default
