experiment_name: qsp_circuit_spin_uniform_legacy-blockencoding
problem:
  n_key: 4
  objective_function: -x0 * x1 + 2 * x1 + 1.5 * x1 * x2 * x3 + x3 -1
  variable_type: spin

algorithm:
  method: qsp
  initial_state: uniform
  qsp_params:
    qsp_degree: 9
    #従来のQSPのブロック埋め込み手法
    blockencoding_method: legacy 

simulation:
  convergence_backend: circuit
  backend: statevector
  max_iterations: 20
  seed: 123

execution:
  num_trials: 10

circuit_assets:
  build: true

circuit_evaluation:
  optimization_level: 1
  basis_gates: Default
