experiment_name: qsp_nocircuit_spin_example

problem:
  n_key: 4
  objective_function: x0 + x1 + x2 + x3
  variable_type: spin

algorithm:
  method: qsp
  initial_state: uniform
  state_prep_params: {}
  qsp_params:
    qsp_degree: 109

simulation:
  convergence_backend: nocircuit
  backend: statevector
  max_iterations: 30
  seed: 1

execution:
  num_trials: 20

circuit_assets:
  build: true

circuit_evaluation:
  optimization_level: 1
  basis_gates: Default
