experiment_name: qsp_nocircuit_spin

problem:
  n_key: 4
  objective_function: -x0 * x1 + 2 * x1 + 1.5 * x1 * x2 * x3 + x3 -1
  variable_type: spin

algorithm:
  method: qsp
  initial_state: uniform
  qsp_params:
    qsp_degree: 9

simulation:
  convergence_backend: nocircuit
  backend: statevector
  max_iterations: 20
  seed: 1

execution:
  num_trials: 100

circuit_assets:
  build: false

circuit_evaluation:
  optimization_level: 1
  basis_gates: Default
