
experiment_name: qsp_spin_analytical_degree_31

problem:
  n_key: 8
  objective_function: x0 + x1 - x2 - x3 + 2*x4 - 2*x5 + 0.5*x6 - 0.5*x7
  variable_type: spin

algorithm:
  method: qsp
  initial_state: hadamard
  qsp_params:
    qsp_degree: 31
    threshold: 0.0

execution:
  num_trials: 50

simulation:
  backend: analytical
  max_iterations: 64
  seed: 0
